<!doctype html>
<html class="no-js" lang="ru">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>WorkHAus | Home</title>
    <meta name="description" content="Мастер на час">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicon -->
<#--    <link rel="shortcut icon" type="image/x-icon" href="/assets/images/favicon.ico">-->

    <!-- CSS
    ========================= -->

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css">

    <!-- Plugins CSS -->
    <link rel="stylesheet" href="/assets/css/plugins.css">

    <!-- Main Style CSS -->
    <link rel="stylesheet" href="/assets/css/style.css">

    <!-- Modernizer JS -->
    <script src="/assets/js/vendor/modernizr-2.8.3.min.js"></script>
</head>

<body>
<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
    (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
        m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
    (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

    ym(64717183, "init", {
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:true,
        webvisor:true
    });
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/64717183" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
<!-- Main Wrapper Start -->
<div class="main-wrapper">
    <!-- header-area start -->
    <header class="header header-sticky is-sticky">
        <!-- header-top start -->
        <div id="main-menu" class="header-top inner-header">
            <div class="container">
                <div class="row header-top-inner">
                    <div class="col-lg-4">
                        <div class="logo">
                            <a href="/"><img src="/assets/images/logo/logo-2.png" alt=Мастер на час"></a>
                        </div>
                    </div>
                    <div class="col-lg-8">
                        <div class="main-menu">
                            <nav class="main-navigation">
                                <ul>
                                    <li class="active"><a href="#slider">Домой</a></li>
                                    <li class="smooth-scroll"><a href="#about">О нас</a></li>
                                    <li><a href="#feature">Услуги</a></li>
                                    <li><a href="#contact">Контакты</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <div class="col">
                        <!-- mobile-menu start -->
                        <div class="mobile-menu d-block d-lg-none"></div>
                        <!-- mobile-menu end -->
                    </div>
                </div>
            </div>
        </div>
        <!-- Header-top end -->
    </header>
    <!-- Header-area end -->

    <!-- Hero Slider start -->
    <div class="hero-slider hero-slider-bg-1" id="slider">
        <div class="single-slide" style="background-image: url(/assets/images/slider/slider-02.png)">
            <!-- Hero Content One Start -->
            <div class="hero-content-one container">
                <div class="row align-items-center">
                    <div class="col-lg-6 col-md-8">
                        <div class="slider-text-info white-text">
                            <h1>Сервисная служба <br>мастер на час</h1>
                            <p>Квалифицированный состав специалистов, поможет Вам в выполнении бытовых <a href="#feature">задач</a></p>
                            <p>Если у Вас сломался холодильник, упала полка, или же вы хотите
                                покрыть ванну жидким акрилом и ищите квалифицированного специалиста,
                                который справится с поставленной задачей, то воспользуйте кнопкой ниже
                                оставив нам заявку, после обработки заявки с Вами свяжется специалит и предложит решение</p>
                            <div class="slider-button">
                                <a href="/requestcustomer" class="slider-btn uppercase"><span><i class="fa fa-send-o"></i>Оставить заявку</span></a>
                            </div>
                            <br>
                            <div class="slider-button">
                                <a href="https://teleg.run/MasterHaus_bot" class="slider-btn uppercase"><span><i class="fa fa-send-o"></i>Telegramm __Bot</span></a>
                            </div>

                        </div>
                    </div>
                    <div class="col-lg-3 offset-lg-2 col-md-4 text-center">
                        <div class="slider-inner-imge-2 banner-right">
                            <img src="/assets/images/slider/inner-1.png" alt="">
                        </div>
                    </div>
                </div>
            </div>
            <!-- Hero Content One End -->
        </div>
    </div>
    <!-- Hero Slider end -->



<#--    <!-- Hero Slider start &ndash;&gt;-->
<#--    <div class="hero-slider hero-slider-bg-1 overlay-left-right-02 bg-grey" id="slider">-->
<#--        <div class="single-slide" style="background-image: url(assets/images/slider/slider-03.png)">-->
<#--            <!-- Hero Content One Start &ndash;&gt;-->
<#--            <div class="hero-content-one container">-->
<#--                <div class="row align-items-center">-->
<#--                    <div class="col-lg-6 col-md-8">-->
<#--                        <div class="slider-text-info">-->
<#--                            <h1>Carroll an Awesome <br>Travel App.</h1>-->
<#--                            <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>-->
<#--                            <div class="slider-button">-->
<#--                                <a href="#" class=" slider-btn uppercase"><span><i class="fa fa-apple"></i>Apple store</span></a>-->
<#--                                <a href="#" class="slider-btn uppercase"><span><i class="fa fa-send-o"></i>Google play</span></a>-->
<#--                            </div>-->

<#--                        </div>-->
<#--                    </div>-->
<#--                    <div class="col-lg-3 offset-lg-2 col-md-4 text-center">-->
<#--                        <div class="slider-inner-imge-2 banner-right">-->
<#--                            <img src="/assets/images/slider/inner-1.png" alt="">-->
<#--                        </div>-->
<#--                    </div>-->
<#--                </div>-->
<#--            </div>-->
<#--            <!-- Hero Content One End &ndash;&gt;-->
<#--        </div>-->
<#--    </div>-->
<#--    <!-- Hero Slider end &ndash;&gt;-->

    <!-- About Area Start -->
    <div id="about" class="about-area bg-grey section-ptb">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6  order-2 order-lg-1">
                    <div class="about-content-two">
                        <div class="about-title-two">
                            <h2>О компании</h2>
                            <h3>WorkHaus.online это сервис по подбору нужного специалиста </h3>
                        </div>
                        <p> Оказываем услуги по любым бытовым вопросам для населения и бизна.С нами сотрудничают лучшие специалисты Вашего города
                            Благодаря тщательному отбору специалистов мы можем обеспечить качественное и оперативное решение поставленных задач
                            С помощью нашего сервиса вы можете воспользоваться услугами мастеров таких специализаций как: электрик, сантехник,сборщик мебели,мастер на час,жена на час,плотник,плиточник, штукатур моляр,установщик бытовой техники, ремонт техники,грузчики разнорабочие,клининг,it-специалист и многих других
                            Сервис сотрудничает с большим числом мастеров что позволяет нам работать по доступным для вас расценкам на все виды работ,оперативное принятие заявки и выезд мастера в нужное,а главное удобное для вас время
                            Мы следим за качеством выполнения работ,по этому проводим постоянное повышение квалификации специалистов</p>
                        <p>Присоединяйтесь к нам в социальных сетях</p>
                        <div class="about-social-link">
                            <a href="https://vk.com/albert_777"><i class="fa fa-facebook"></i></a>
                            <a href="https://vk.com/albert_777"><i class="fa fa-twitter"></i></a>
                            <a href="https://vk.com/albert_777"><i class="fa fa-linkedin"></i></a>
                            <a href="https://vk.com/albert_777"><i class="fa fa-instagram"></i></a>
                            <a href="https://vk.com/albert_777"><i class="fa fa-dribbble"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 order-1 order-lg-2">
                    <div class="about-image text-center wow fadeInBottom" data-wow-duration="1s">
                        <img src="/assets/images/about/01.png" alt="Мастер на час">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- About Area End -->

    <!-- Feature Area Start  -->
    <div  id="feature" class="feature-area section-ptb">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 ml-auto mr-auto">
                    <div class="section-title">
                        <h2>Выполняем следующие работы</h2>
<#--                        <p>Наши специалисты готовы приступить </p>-->
                    </div>
                </div>
            </div>
            <div class="row align-items-center feature-area-inner">
                <div class="col-lg-4 order-md-2 col-md-6 order-lg-1">
                    <div class="feature-content-inner">
                        <div class="single-feature text-right row-reverse">
                            <div class="feature-icon">
                                <i class="ion-ios-speedometer-outline"></i>
                            </div>
                            <div class="feature-content">
                                <div class="feature-text">
<#--&lt;#&ndash;ываыва&ndash;&gt;-->
<#--                                                    -->
<#--                                                        <ul class="nav side-menu">-->
<#--                                                            <li><a><i class="fa fa-bug"></i> Additional Pages <span class="fa fa-chevron-down"></span></a>-->
<#--                                                                <ul class="nav child_menu" style="display: none">-->
<#--                                                                    <li><a href="e_commerce.html">E-commerce</a>-->
<#--                                                                    </li>-->
<#--                                                                    <li><a href="projects.html">Projects</a>-->
<#--                                                                    </li>-->
<#--                                                                    <li><a href="project_detail.html">Project Detail</a>-->
<#--                                                                    </li>-->
<#--                                                                    <li><a href="contacts.html">Contacts</a>-->
<#--                                                                    </li>-->
<#--                                                                    <li><a href="profile.html">Profile</a>-->
<#--                                                                    </li>-->
<#--                                                                </ul>-->
<#--                                                            </li>-->
<#--                                                            <li><a><i class="fa fa-windows"></i> Extras <span class="fa fa-chevron-down"></span></a>-->
<#--                                                                <ul class="nav child_menu" style="display: none">-->
<#--                                                                    <li><a href="page_404.html">404 Error</a>-->
<#--                                                                    </li>-->
<#--                                                                    <li><a href="page_500.html">500 Error</a>-->
<#--                                                                    </li>-->
<#--                                                                    <li><a href="plain_page.html">Plain Page</a>-->
<#--                                                                    </li>-->
<#--                                                                    <li><a href="login.html">Login Page</a>-->
<#--                                                                    </li>-->
<#--                                                                    <li><a href="pricing_tables.html">Pricing Tables</a>-->
<#--                                                                    </li>-->

<#--                                                                </ul>-->
<#--                                                            </li>-->
<#--                                                            <li><a><i class="fa fa-laptop"></i> Landing Page <span class="label label-success pull-right">Coming Soon</span></a>-->
<#--                                                            </li>-->
<#--                                                        </ul>-->

<#--                                    <script src="/static/js/custom.js"></script>-->
<#--                                    &lt;#&ndash;ываыва&ndash;&gt;-->


                                    <h4>Мелкий бытовой ремонт</h4>
                                    <ul>
                                        <li>Установка карнизов для штор</li>
                                        <li>Монтаж кронштейнов для TV</li>
                                        <li>Установка турников</li>
                                        <li>Навес полок на стену</li>
                                        <li>Установка навесных шкафов</li>
                                        <li>Установка зеркал на стену</li>
                                        <li>Установка напольных плинтусов</li>
                                        <li>Врезка дверных замков</li>
                                        <li>Установка сушилки для белья</li>
                                        <li>Установка экрана под ванну</li>
                                        <li>Установка экрана на батарею</li>
                                        <li>Установка вентиляционных решеток</li>
                                        <li>Сверление отверстий</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="single-feature  text-right row-reverse">
                            <div class="feature-icon">
                                <i class="ion-ios-chatboxes-outline"></i>
                            </div>
                            <div class="feature-content">
                                <div class="feature-text">

                                    <h4>Работы выполняемые плотником</h4>
                                    <ul>
                                        <li>Замена замков</li>
                                        <li>Врезка и установка моек</li>
                                        <li>Сборка мебели</li>
                                    </ul>

                                </div>
                            </div>
                        </div>
                        <div class="single-feature  text-right row-reverse">
                            <div class="feature-icon">
                                <i class="ion-ios-lightbulb-outline"></i>
                            </div>
                            <div class="feature-content">
                                <div class="feature-text">
                                    <h4>Электромонтажные работы</h4>

                                    <ul>
                                        <li>Установка розеток, установка выключателей</li>
                                        <li>Сборка и установка люстр, светильников</li>
                                        <li>Установка счётчиков, замена счетчиков</li>
                                        <li>Установка автоматов, замена автоматов</li>
                                        <li>Устройство электропроводки</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="single-feature  text-right row-reverse">
                            <div class="feature-icon">
                                <i class="ion-ios-lightbulb-outline"></i>
                            </div>
                            <div class="feature-content">
                                <div class="feature-text">
                                    <h4>Установка</h4>

                                    <ul>
                                        <li>Стиральную машину</li>
                                        <li>Посудомоечную машину</li>
                                        <li>Смеситель</li>
                                        <li>Раковину</li>
<#--                                        <li>Вытяжку</li>-->
<#--                                        <li>Вентилятор</li>-->
<#--                                        <li>Розетки</li>-->
<#--                                        <li>Точечные светильники</li>-->
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4  order-md-1 col-md-12 order-lg-2">
                    <div class="feature-image text-center">
<#--                        <img src="/assets/images/screenshot/service.png" alt="">-->
                    </div>
                </div>
                <div class="col-lg-4  order-md-3 col-md-6 order-lg-3 ">
                    <div class="feature-content">
                        <div class="single-feature">
                            <div class="feature-icon">
                                <i class="ion-ios-world-outline"></i>
                            </div>
                            <div class="feature-content">
                                <div class="feature-text">



                                    <h4>Сантехнические работы</h4>
                                    <ul>
                                        <li>Замена канализационных труб</li>
                                        <li>Замена водопроводных труб</li>
                                        <li>Замена смесителя</li>
                                        <li>Ремонт, обслуживание фильтров очистки воды</li>
                                        <li>Замена счетчиков воды</li>
                                        <li>Установка ванны,установка раковины, установка унитаза</li>
                                        <li>Сборка душевой кабины, ремонт душевой кабины</li>
                                        <li>Установка подключение стиральных и посудомоечных машин</li>
                                        <li>Герметизация ванн, душевых кабин</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="single-feature">
                            <div class="feature-icon">
                                <i class="ion-ios-gear-outline"></i>
                            </div>
                            <div class="feature-content">
                                <div class="feature-text">
                                    <h4>Прочистка</h4>
                                    <ul>
                                        <li>Засоры канализации</li>
                                        <li>Раковину</li>
                                        <li>Унитаз</li>
                                        <li>Душевую кабину</li>
                                        <li>Вентиляцию</li>
                                        <li>Вытяжку</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="single-feature">
                            <div class="feature-icon">
                                <i class="ion-ios-cloud-download-outline"></i>
                            </div>
                            <div class="feature-content">
                                <div class="feature-text">
                                    <h4>Повесить, закрепить</h4>
                                    <ul>
                                    <li>Полки</li>
                                    <li>Шкафы</li>
                                    <li>Люстры</li>
                                    <li>Картины</li>
                                    <li>Зеркала</li>
                                    <li>Шторы</li>
                                    <li>Гардины</li>
                                    <li>Телевизоры</li>
                                    <li>Кронштейны</li>
                                    <li>Турник</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Feature Area End -->

<#--    <!-- Video Area Start &ndash;&gt;-->
<#--    <div class="video-area theme-bg video-banner-overlay">-->
<#--        <div class="video-info text-center">-->
<#--            <div class="vedio-popup-btn wow pulse" data-wow-duration="1s">-->
<#--                <a href="http://www.youtube.com/watch?v=0O2aH4XLbto" class="popup-youtube"> <img src="/assets/images/icon/iconroject.png" alt=""> </a>-->
<#--            </div>-->
<#--            <h3 class="video-title text-white">Video presentation</h3>-->
<#--        </div>-->
<#--    </div>-->
<#--    <!-- Video Area End &ndash;&gt;-->

<#--    <!-- Project Count Area Start &ndash;&gt;-->
<#--    <div class="project-count-area">-->
<#--        <div class="container">-->
<#--            <div class="row">-->
<#--                <div class="col">-->
<#--                    <div class="project-count-inner project-bg wow fadeInBottom" data-wow-duration="1s">-->
<#--                        <div class="row">-->
<#--                            <div class="col-lg-3 col-sm-6">-->
<#--                                <!-- counter start &ndash;&gt;-->
<#--                                <div class="counter text-center">-->
<#--                                    <h3 class="counter-active">241</h3>-->
<#--                                    <p>APP Downloads</p>-->
<#--                                </div>-->
<#--                                <!-- counter end &ndash;&gt;-->
<#--                            </div>-->
<#--                            <div class="col-lg-3 col-sm-6">-->
<#--                                <!-- counter start &ndash;&gt;-->
<#--                                <div class="counter text-center">-->
<#--                                    <h3 class="counter-active">531</h3>-->
<#--                                    <p>Happy Clients</p>-->
<#--                                </div>-->
<#--                                <!-- counter end &ndash;&gt;-->
<#--                            </div>-->
<#--                            <div class="col-lg-3 col-sm-6">-->
<#--                                <!-- counter start &ndash;&gt;-->
<#--                                <div class="counter text-center">-->
<#--                                    <h3 class="counter-active">171</h3>-->
<#--                                    <p>Total App Rates</p>-->
<#--                                </div>-->
<#--                                <!-- counter end &ndash;&gt;-->
<#--                            </div>-->
<#--                            <div class="col-lg-3 col-sm-6">-->
<#--                                <!-- counter start &ndash;&gt;-->
<#--                                <div class="counter text-center">-->
<#--                                    <h3 class="counter-active">331</h3>-->
<#--                                    <p>Awrds Winned</p>-->
<#--                                </div>-->
<#--                                <!-- counter start &ndash;&gt;-->
<#--                            </div>-->
<#--                        </div>-->
<#--                    </div>-->
<#--                </div>-->
<#--            </div>-->
<#--        </div>-->
<#--    </div>-->
<#--    <!-- Project Count Area End &ndash;&gt;-->

<#--    <!-- Pricing Packages Start &ndash;&gt;-->
<#--    <div id="pricing" class="priceing-package-area section-ptb">-->
<#--        <div class="container">-->
<#--            <div class="row">-->
<#--                <div class="col-lg-7 ml-auto mr-auto">-->
<#--                    <div class="section-title pb--50">-->
<#--                        <h2>OUR Pricing Table</h2>-->
<#--                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam, fugiat, accusamus! Consequatur suscipit numquam cumque.</p>-->
<#--                    </div>-->
<#--                </div>-->
<#--            </div>-->
<#--            <div class="row no-gutters ext-plr-30">-->
<#--                <div class="col-lg-4 col-md-6 order-lg-1 order-1">-->
<#--                    <!-- single-priceing Start &ndash;&gt;-->
<#--                    <div class="single-priceing text-center">-->
<#--                        <div class="table-header">-->
<#--                            <h5>Basic Plan</h5>-->
<#--                            <h3>$49.00</h3>-->
<#--                        </div>-->
<#--                        <ul class="pricing-list">-->
<#--                            <li>Marketing Metup</li>-->
<#--                            <li class="not">Free Coffy.</li>-->
<#--                            <li>Support Papers</li>-->
<#--                            <li class="not">Policy System</li>-->
<#--                            <li class="not">One Time Support</li>-->
<#--                            <li></li>-->
<#--                        </ul>-->
<#--                        <div class="chose-btn">-->
<#--                            <a href="#" class="btn choose-button">Choose Now </a>-->
<#--                        </div>-->
<#--                    </div>-->
<#--                    <!-- single-priceing End &ndash;&gt;-->
<#--                </div>-->
<#--                <div class="col-lg-4 col-md-6 ml-auto mr-auto order-lg-2 order-3">-->
<#--                    <!-- single-priceing Start &ndash;&gt;-->
<#--                    <div class="single-priceing text-center active">-->
<#--                        <div class="table-header">-->
<#--                            <h5>Basic Plan</h5>-->
<#--                            <h3>$99.00</h3>-->
<#--                        </div>-->
<#--                        <ul class="pricing-list">-->
<#--                            <li>Marketing Metup</li>-->
<#--                            <li>Free Coffy.</li>-->
<#--                            <li>Support Papers</li>-->
<#--                            <li>Policy System</li>-->
<#--                            <li>One Time Support</li>-->
<#--                            <li></li>-->
<#--                        </ul>-->
<#--                        <div class="chose-btn">-->
<#--                            <a href="#" class="btn choose-button">Choose Now </a>-->
<#--                        </div>-->
<#--                    </div>-->
<#--                    <!-- single-priceing End &ndash;&gt;-->
<#--                </div>-->
<#--                <div class="col-lg-4 col-md-6 order-lg-3 order-2">-->
<#--                    <!-- single-priceing Start &ndash;&gt;-->
<#--                    <div class="single-priceing last text-center">-->
<#--                        <div class="table-header">-->
<#--                            <h5>Basic Plan</h5>-->
<#--                            <h3>$60.00</h3>-->
<#--                        </div>-->
<#--                        <ul class="pricing-list">-->
<#--                            <li>Marketing Metup</li>-->
<#--                            <li>Free Coffy.</li>-->
<#--                            <li>Support Papers</li>-->
<#--                            <li class="not">Policy System</li>-->
<#--                            <li class="not">One Time Support</li>-->
<#--                            <li></li>-->
<#--                        </ul>-->
<#--                        <div class="chose-btn">-->
<#--                            <a href="#" class="btn choose-button">Choose Now </a>-->
<#--                        </div>-->
<#--                    </div>-->
<#--                    <!-- single-priceing End &ndash;&gt;-->
<#--                </div>-->
<#--            </div>-->
<#--        </div>-->
<#--    </div>-->
<#--    <!-- Pricing Packages End &ndash;&gt;-->

<#--    <!-- Testimonial Area Start &ndash;&gt;-->
<#--    <div id="testimonial" class="testimonial-area section-ptb bg-testimonial">-->
<#--        <div class="container">-->
<#--            <div class="row">-->
<#--                <div class="col-lg-8 ml-auto mr-auto">-->
<#--                    <div class="testimonial-content testimonial-active">-->
<#--                        <!-- single-testimonial start &ndash;&gt;-->
<#--                        <div class="single-testimonial">-->
<#--                            <div class="client-image">-->
<#--                                <img src="/assets/images/review/03.jpg" alt="">-->
<#--                            </div>-->
<#--                            <div class="client-rating">-->
<#--                                <ul class="d-flex">-->
<#--                                    <li><a href="#"><i class="fa fa-star"></i></a></li>-->
<#--                                    <li><a href="#"><i class="fa fa-star"></i></a></li>-->
<#--                                    <li><a href="#"><i class="fa fa-star"></i></a></li>-->
<#--                                    <li><a href="#"><i class="fa fa-star"></i></a></li>-->
<#--                                    <li><a href="#"><i class="fa fa-star-o"></i></a></li>-->
<#--                                </ul>-->
<#--                            </div>-->
<#--                            <div class="testimonial-text">-->
<#--                                <p class="client-texe-dec">Aenean sollicitudin, lorem quis bibendum auctor This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet. , nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris.</p>-->
<#--                                <div class="test-author">-->
<#--                                    <h3>Mickel Harice </h3>-->
<#--                                    <p>CEO - of Teritech</p>-->
<#--                                </div>-->
<#--                            </div>-->
<#--                        </div>-->
<#--                        <!-- single-testimonial end &ndash;&gt;-->
<#--                        <!-- single-testimonial start &ndash;&gt;-->
<#--                        <div class="single-testimonial">-->
<#--                            <div class="client-image">-->
<#--                                <img src="/assets/images/review/01.jpg" alt="">-->
<#--                            </div>-->
<#--                            <div class="client-rating">-->
<#--                                <ul class="d-flex">-->
<#--                                    <li><a href="#"><i class="fa fa-star"></i></a></li>-->
<#--                                    <li><a href="#"><i class="fa fa-star"></i></a></li>-->
<#--                                    <li><a href="#"><i class="fa fa-star"></i></a></li>-->
<#--                                    <li><a href="#"><i class="fa fa-star"></i></a></li>-->
<#--                                    <li><a href="#"><i class="fa fa-star-o"></i></a></li>-->
<#--                                </ul>-->
<#--                            </div>-->
<#--                            <div class="testimonial-text">-->
<#--                                <p class="client-texe-dec">Aenean sollicitudin, lorem quis bibendum auctor This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet. , nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris.</p>-->
<#--                                <div class="test-author">-->
<#--                                    <h3>Mickel Harice </h3>-->
<#--                                    <p>CEO - of Teritech</p>-->
<#--                                </div>-->
<#--                            </div>-->
<#--                        </div>-->
<#--                        <!-- single-testimonial end &ndash;&gt;-->
<#--                        <!-- single-testimonial start &ndash;&gt;-->
<#--                        <div class="single-testimonial">-->
<#--                            <div class="client-image">-->
<#--                                <img src="/assets/images/review/02.jpg" alt="">-->
<#--                            </div>-->
<#--                            <div class="client-rating">-->
<#--                                <ul class="d-flex">-->
<#--                                    <li><a href="#"><i class="fa fa-star"></i></a></li>-->
<#--                                    <li><a href="#"><i class="fa fa-star"></i></a></li>-->
<#--                                    <li><a href="#"><i class="fa fa-star"></i></a></li>-->
<#--                                    <li><a href="#"><i class="fa fa-star"></i></a></li>-->
<#--                                    <li><a href="#"><i class="fa fa-star-o"></i></a></li>-->
<#--                                </ul>-->
<#--                            </div>-->
<#--                            <div class="testimonial-text">-->
<#--                                <p class="client-texe-dec">Aenean sollicitudin, lorem quis bibendum auctor This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet. , nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris.</p>-->
<#--                                <div class="test-author">-->
<#--                                    <h3>Mickel Harice </h3>-->
<#--                                    <p>CEO - of Teritech</p>-->
<#--                                </div>-->
<#--                            </div>-->
<#--                        </div>-->
<#--                        <!-- single-testimonial end &ndash;&gt;-->
<#--                    </div>-->
<#--                </div>-->
<#--            </div>-->
<#--        </div>-->
<#--    </div>-->
<#--    <!-- Testimonial Area End &ndash;&gt;-->

<#--    <!-- Screenshot Area Tow Start &ndash;&gt;-->
<#--    <div id="screnshot" class="screnshot-area-tow section-ptb">-->
<#--        <div class="container">-->
<#--            <div class="row">-->
<#--                <div class="col-lg-7 ml-auto mr-auto">-->
<#--                    <div class="section-title">-->
<#--                        <h2>APP Screenshots</h2>-->
<#--                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam, fugiat, accusamus! Consequatur suscipit numquam cumque.</p>-->
<#--                    </div>-->
<#--                </div>-->
<#--            </div>-->
<#--            <!-- Screnshot Content Two Start&ndash;&gt;-->
<#--            <div class="screnshot-content-two">-->
<#--                <div class="row screenshot-tow-active">-->
<#--                    <div class="col-lg-4">-->
<#--                        <!-- Singel Screenshot Start &ndash;&gt;-->
<#--                        <div class="singel-screenshot">-->
<#--                            <span class="overlay-bg"></span>-->
<#--                            <a href="/assets/images/screenshot/01.png" class="img-poppu">-->
<#--                                <span class="single-img overlay-bg">-->
<#--                                    <img src="/assets/images/screenshot/01.png" alt="">-->
<#--                                </span>-->
<#--                            </a>-->
<#--                        </div>-->
<#--                        <!-- Singel Screenshot End &ndash;&gt;-->
<#--                    </div>-->
<#--                    <div class="col-lg-4">-->
<#--                        <!-- Singel Screenshot Start &ndash;&gt;-->
<#--                        <div class="singel-screenshot">-->
<#--                            <span class="overlay-bg"></span>-->
<#--                            <a href="/assets/images/screenshot/02.png" class="img-poppu">-->
<#--                                <span class="single-img overlay-bg">-->
<#--                                    <img src="/assets/images/screenshot/02.png" alt="">-->
<#--                                </span>-->
<#--                            </a>-->
<#--                        </div>-->
<#--                        <!-- Singel Screenshot End &ndash;&gt;-->
<#--                    </div>-->
<#--                    <div class="col-lg-4">-->
<#--                        <!-- Singel Screenshot Start &ndash;&gt;-->
<#--                        <div class="singel-screenshot">-->
<#--                            <span class="overlay-bg"></span>-->
<#--                            <a href="/assets/images/screenshot/03.png" class="img-poppu">-->
<#--                                <span class="single-img overlay-bg">-->
<#--                                    <img src="/assets/images/screenshot/03.png" alt="">-->
<#--                                </span>-->
<#--                            </a>-->
<#--                        </div>-->
<#--                        <!-- Singel Screenshot End &ndash;&gt;-->
<#--                    </div>-->
<#--                    <div class="col-lg-4">-->
<#--                        <!-- Singel Screenshot Start &ndash;&gt;-->
<#--                        <div class="singel-screenshot">-->
<#--                            <span class="overlay-bg"></span>-->
<#--                            <a href="/assets/images/screenshot/04.png" class="img-poppu">-->
<#--                                <span class="single-img overlay-bg">-->
<#--                                    <img src="/assets/images/screenshot/04.png" alt="">-->
<#--                                </span>-->
<#--                            </a>-->
<#--                        </div>-->
<#--                        <!-- Singel Screenshot End &ndash;&gt;-->
<#--                    </div>-->
<#--                    <div class="col-lg-4">-->
<#--                        <!-- Singel Screenshot Start &ndash;&gt;-->
<#--                        <div class="singel-screenshot">-->
<#--                            <span class="overlay-bg"></span>-->
<#--                            <a href="/assets/images/screenshot/01.png" class="img-poppu">-->
<#--                                <span class="single-img overlay-bg">-->
<#--                                    <img src="/assets/images/screenshot/01.png" alt="">-->
<#--                                </span>-->
<#--                            </a>-->
<#--                        </div>-->
<#--                        <!-- Singel Screenshot End &ndash;&gt;-->
<#--                    </div>-->
<#--                    <div class="col-lg-4">-->
<#--                        <!-- Singel Screenshot Start &ndash;&gt;-->
<#--                        <div class="singel-screenshot">-->
<#--                            <span class="overlay-bg"></span>-->
<#--                            <a href="/assets/images/screenshot/02.png" class="img-poppu">-->
<#--                                <span class="single-img overlay-bg">-->
<#--                                    <img src="/assets/images/screenshot/02.png" alt="">-->
<#--                                </span>-->
<#--                            </a>-->
<#--                        </div>-->
<#--                        <!-- Singel Screenshot End &ndash;&gt;-->
<#--                    </div>-->
<#--                </div>-->
<#--            </div>-->
<#--            <!-- Screnshot Content Two End&ndash;&gt;-->
<#--        </div>-->
<#--    </div>-->
<#--    <!-- Screenshot Area Tow End &ndash;&gt;-->

    <!-- Download Area Start  -->
    <div class="download-area-two section-ptb download-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 ml-auto mr-auto">
                    <div class="section-title text-black">
                        <h2>Для специалистов</h2>
                        <p>Если у Вас есть пару часов свободного времени в течении дня,
                            мы рекомендуем Вам отправить нам краткую анкету,
                            и если Вы пройдете собеседование то получите возможность дополнительного дохода</p>
                    </div>
<#--                    <div class="section-title text-black">-->
<#--                        <h2>Сотрудничество для мастеров</h2>-->
<#--                        <p>Если вы профессионал в своей сфере и постоянно развиваете свои профессиональные навыки,готовы работать-->
<#--                            в динамично развивающейся компании, оставляйте заявку на нашем сайте.</p>-->
<#--                        <p>Свободный график на выгодных условиях.-->
<#--                        <p> Ждём вас в наших рядах.</p>-->
<#--                        <p> Подробную информацию расскажет менеджер после подачи заявки.</p>-->
<#--                    </div>-->
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="download-buttons text-center">
                        <a href="/personworcinterview" class="button"> <i class="fa fa-send-o"></i> Отправить анкету</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Download Area End  -->

    <!-- Contact Area Start -->
    <div id="contact" class="contact-area-two section-ptb">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="contact-info-container">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="contact-title">
                                    <h2>По вопросу сотрудничества</h2>
                                    <p>По вопросам сотрудничества Вы можете обратиться к нам по ниже приведенным контактным данным. Мы молодая и динамично развивающаяся компания, если вы энергичный и и вообще крутой человек, пиши нам</p>
                                </div>
                                <div class="contact-address">
                                    <ul>
                                        <li><i class="fa fa-phone"></i> <span class="information">г. Руза 8(982) 3633 115 </span></li>
                                        <li><i class="fa fa-phone"></i> <span class="information">г. Миасс 8(952) 5004 727 </span></li>
                                        <br>
                                        <li><i class="fa fa-user"></i> <span class="information">г. Миасс 8(951) 7761 999 </span></li>
                                        <li><i class="fa fa fa-vk"></i> <span class="information"><a href="https://vk.com/albert_777">https://vk.com/albert_777</a> </span></li>
                                        <li><i class="fa fa-envelope-o"></i> <span class="information"><a href="#">yaaal@mail.ru</a></span></li>
                                        <li><i class="fa fa-map-o"></i> <span class="information">Российская федерация</span></li>
                                    </ul>
                                </div>
                            </div>
<#--                            <div class="col-lg-6">-->
<#--                                <form class="contact-form-area" action="mail.php" method="post" id="contact-form">-->
<#--                                    <div class="row contact-form">-->
<#--                                        <div class="form-group col-md-12">-->
<#--                                            <input name="name" class="form-control" placeholder="Как к Вам обращаться?" type="text" id="name">-->
<#--                                        </div>-->
<#--                                        <div class="form-group col-md-12">-->
<#--                                            <input name="email" class="form-control" placeholder="Номер телефона" type="email" id="email">-->
<#--                                        </div>-->
<#--                                        <div class="form-group col-md-12">-->
<#--                                            <input name="subject" class="form-control" placeholder="Причина" type="text" id="subject">-->
<#--                                        </div>-->
<#--                                        <div class="form-group col-md-12">-->
<#--                                            <textarea name="message" class="yourmessage form-control" placeholder="Ваше сообщение"></textarea>-->
<#--                                        </div>-->
<#--                                        <div class="submit-form form-group col-sm-12">-->
<#--                                            <button class="button submit-btn" type="submit"><span>Отправить</span></button>-->
<#--                                            <p class="form-messege"></p>-->
<#--                                        </div>-->
<#--                                    </div>-->
<#--                                </form>-->
<#--                            </div>-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact Area End -->

<#--    <!-- Footer Area Start &ndash;&gt;-->
<#--    <footer class="footer-area">-->
<#--        <div class="footer-content-area fotter-content-two">-->
<#--            <div class="container">-->
<#--                <div class="row">-->
<#--                    <div class="col-lg-12">-->
<#--                        <div class="footer-content fotter-content-two">-->
<#--                            <div class="footer-logo">-->
<#--                                <a href="index.html"><img src="/assets/images/logo/logo.png" alt=""></a>-->
<#--                            </div>-->
<#--                            <p>Copyright © 2018 HasTech. All Rights Reserved</p>-->
<#--                            <div class="social-link">-->
<#--                                <a href="#"><i class="fa fa-facebook"></i></a>-->
<#--                                <a href="#"><i class="fa fa-twitter"></i></a>-->
<#--                                <a href="#"><i class="fa fa-linkedin"></i></a>-->
<#--                                <a href="#"><i class="fa fa-instagram"></i></a>-->
<#--                                <a href="#"><i class="fa fa-dribbble"></i></a>-->
<#--                            </div>-->
<#--                        </div>-->
<#--                    </div>-->
<#--                </div>-->
<#--            </div>-->
<#--        </div>-->
<#--    </footer>-->
<#--    <!-- Footer Area End &ndash;&gt;-->

</div>
<!-- Main Wrapper End -->

<!-- JS
============================================ -->

<!-- jQuery JS -->
<script src="/assets/js/vendor/jquery-1.12.4.min.js"></script>
<!-- Popper JS -->
<script src="/assets/js/popper.min.js"></script>
<!-- Bootstrap JS -->
<script src="/assets/js/bootstrap.min.js"></script>
<!-- Plugins JS -->
<script src="/assets/js/plugins.js"></script>
<!-- Ajax Mail -->
<script src="/assets/js/ajax-mail.js"></script>
<!-- Main JS -->
<script src="/assets/js/main.js"></script>




</body>

</html>